---
image: maven:3.6.3-jdk-11

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ~/.m2

stages:
  - clean
  - lint
  - tests
  - build
  - release
  - package
  - deploy

before_script:
  # TODO: use docker image with make preinstalled.
  - apt update && apt install -y build-essential zip unzip jq
  - echo
  - make help-backend
  - echo
  - make init-backend

# lint:
#   stage: lint
#   script:
#     - make lint-backend

tests:
  stage: tests
  script:
    - make tests-backend

build:
  stage: build
  script:
    - make build-backend
  artifacts:
    paths:
      - modules/**/target/*.jar
    expire_in: 10 minutes

# release:
#   stage: release
#   script:
#     - make release-backend
#   only:
#     - develop

package:
  stage: package
  script:
    - make package-backend
  dependencies:
    - build
  artifacts:
    paths:
      - target/*.zip
    expire_in: 10 minutes
  only:
    - develop
    - main
  

deploy:
  stage: deploy
  script:
    - make deploy-backend
  dependencies:
    - package
  only:
    - develop
    - main